/**
 * Type declarations for the nec2c Emscripten WASM module.
 *
 * The module is loaded via the `createNec2c()` factory function
 * generated by Emscripten with -sMODULARIZE=1 -sEXPORT_NAME=createNec2c.
 */

/** Emscripten filesystem API (subset used by nec2c) */
interface EmscriptenFS {
  writeFile(path: string, data: string | ArrayBufferView): void;
  readFile(path: string, opts: { encoding: "utf8" }): string;
  readFile(path: string): Uint8Array;
  unlink(path: string): void;
  mkdir(path: string): void;
}

/** The nec2c Emscripten module instance */
export interface Nec2cModule {
  /** Emscripten virtual filesystem */
  FS: EmscriptenFS;
  /** Call main() with CLI arguments. Throws on non-zero exit. */
  callMain(args: string[]): number;
}

/** Options for creating the module instance */
interface Nec2cModuleOptions {
  /** Override the path to the .wasm file */
  locateFile?: (path: string, prefix: string) => string;
  /** Suppress stdout/stderr output */
  print?: (text: string) => void;
  printErr?: (text: string) => void;
  /** Called when the module is ready */
  onRuntimeInitialized?: () => void;
}

/** Factory function generated by Emscripten -sMODULARIZE */
declare function createNec2c(options?: Nec2cModuleOptions): Promise<Nec2cModule>;
export default createNec2c;
